const AUTH_ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    ISLOGGED: "ISLOGGED"
}

const USER_ACTIONS = {
    SET_DATA: 'SET_DATA',
    CLEAR_DATA: 'CLEAR_DATA'
}

const FAMILIAR_ACTIONS = {
    DELETE_FAMILIAR: 'DELETE_FAMILIAR',
    ADD_FAMILIAR: 'ADD_FAMILIAR',
    GET_ALL_FAMILIAR: 'GET_ALL_FAMILIAR',
    CLEAR_DATA: 'CLEAR_DATA' 
}

export { AUTH_ACTIONS, USER_ACTIONS, FAMILIAR_ACTIONS } 