const AUTH_ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    ISLOGGED: "ISLOGGED"
}

const GLOBAL_STYLES_ACTIONS = {
    CHANGE_NAVIGATION: 'CHANGE_NAVIGATION'
}

export { AUTH_ACTIONS, GLOBAL_STYLES_ACTIONS } 