const AUTH_ACTIONS = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    ISLOGGED: "ISLOGGED"
}

const USER_ACTIONS = {
    SET_DATA: 'SET_DATA',
    CLEAR_DATA: 'CLEAR_DATA'
}

export { AUTH_ACTIONS, USER_ACTIONS } 